package:
  name: "falwa"
  version: "1.2.1"

source:
  path: ../

requirements:
  build:
    - gfortran
    - python==3.10
    - numpy==1.22.3
  run:
    - python==3.10
    - numpy==1.22.3

test:
  imports:
    - falwa

about:
  home: https://github.com/csyhuang/hn2016_falwa
  license: MIT
  license_family: MIT
  summary: Finite amplitude local wave activity package