name: falwa_env_dev

channels:
- conda-forge
- defaults

dependencies:
- python=3.10
- numpy=1.22.3
- scipy=1.9
- xarray=2023.2.0 # This is optional
- pytest
# Below are for developers
- wheel
- twine
- conda-build

