name: falwa_env_dev

channels:
- conda-forge
- defaults

dependencies:
- python=3.10
- numpy=1.22.3
- scipy=1.9
- pytest=7.4.0
- xarray=2023.2.0 # This is optional
- netCDF4=1.5.8
- matplotlib=3.5.3
- gfortran
# Below are for developers
- wheel
- twine
- conda-build

