name: test_f2py_2021 # default is root
channels:
  - conda-forge
  - bioconda
dependencies:         # everything under this, installed by conda
  - numpy
  - scipy
  - netcdf4
  - pytest
  - jupyterlab
  - matplotlib=2.2.2
  - ecmwfapi # This will be deprecated soon
  #- cartopy # This packages is optional for plotting
  #- earthengine-api # This package is optional for running analysis on Google Earth Engine
  ## The packages below are optional for downloading ERA5
  #- pip
  #- pip:
  #    - cdsapi