jupyter nbconvert --execute --to notebook --inplace ../notebooks/nh2018_science/demo_script_for_nh2018.ipynb
jupyter nbconvert --execute --to notebook --inplace ../notebooks/nh2018_science/demo_script_for_nh2018_with_xarray.ipynb
jupyter nbconvert --execute --to notebook --inplace ../notebooks/nh2018_science/nhn22_reference_states.ipynb
jupyter nbconvert --execute --to notebook --inplace ../notebooks/sandy/sandy_lwa_plots.ipynb
jupyter nbconvert --execute --to notebook --inplace ../notebooks/simple/BarotropicField_example.ipynb
jupyter nbconvert --execute --to notebook --inplace ../notebooks/simple/Example_barotropic.ipynb
jupyter nbconvert --execute --to notebook --inplace ../notebooks/simple/Example_qgpv.ipynb
jupyter nbconvert --execute --to notebook --inplace ../notebooks/lubis_et_al_2025/develop_ncforce_interface.ipynb
jupyter nbconvert --execute --to notebook --inplace ../notebooks/lubis_et_al_2025/ncforce_qgdataset_2.1.0.ipynb
jupyter nbconvert --execute --to notebook --inplace ../notebooks/lubis_et_al_2025/ncforce_qgfield_2.1.0.ipynb